#include "pipelines/resolve_gbuffer/ResolveGBuffer.hpp"
#include "pipelines/terrain/Terrain.hpp"
#include "pipelines/tonemap/Tonemap.hpp"
#include "pipelines/skybox/Skybox.hpp"
#include "pipelines/static_mesh/StaticMesh.hpp"