name: format

on:
  push:
    paths:
      - '**.hpp'
      - '**.cpp'
      - '**.clang-format'

permissions:
  contents: read

jobs:
  check-format-and-tidy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '17'
        fallback-style: 'none'
